### ISSUE TITLE
Open sourced and not working

### ISSUE THREAD

**Issue by NotsalgiaHacker** [lunasoldstuff/nitropy#1]
This repl.it is quite stupid. If you want to make a key system so only certain people can access it, you have to use hashes or convert it to .exe . Otherwise, people can edit it through a text document and steal the source code and remove the password system. Also, there is no specific file to run and README.MD is very useless and does not give you instructions on how to use it. I checked all files and none of them seem to be completed code to make the gen+checker work. I don't think its a virus but it could be potentially hidden. Don't waste your time downloading!

**Comment by stampylongr** [comment]
> This repl.it is quite stupid.

This is on GitHub, not <https://repl.it>, but OK.

> I checked all files and none of them seem to be completed code to make the gen+checker work.

I didn't even try to complete this, as this repository is in the @lunasoldstuff organization for a reason.

The original code is [here](https://github.com/kieronia/nitrogen), which can work with some effort.

> Otherwise, people can edit it through a text document and steal the source code and remove the password system.

The entire point of being open-source is that people can view the code, use it/edit it/audit it, and contribute contributions back if they wanted to. The entire purpose of the original repository was to provide a safer command-line script that did what most of those shady EXEs you mentioned claimed to do.

The reason I tried to start this fork was because the original program was littered with bugs, and it was hard to use.

> If you want to make a key system so only certain people can access it, you have to use hashes or convert it to .exe

This is not used in anything important, or anything for that matter. This is not a "key Discord system" or something like that.

And regarding the key system thing, code can be public and still be secure. There's a reason why OpenPGP is one of the most-used cryptography libraries in the world, and that's because it's open-source.

---

Judging from your profile, you are new here. This *entire* website is dedicated to hosting open-source projects, both big and small, and it's been doing it since 2008, and is now valued at over $2 billion.

I'm closing this issue, but feel free to ask more questions about open-source software!

**Comment by stampylongr** [comment]
P.S. there is no password system. I have no idea where you got that from.
